### ISSUE TITLE
System::getContainer() services shouldn't go into the class constructor

### ISSUE THREAD

**Issue by qzminski** [contao/contao-rector#1]
Input:

```php
public function method()
{
    $service = System::getContainer()->get(\App\Service::class);
}
```

Output:

```php
public function __construct(private \App\Service $service)
{
}

public function method()
{
    $service = $this->service;
}
```

Problem:

Getting a service from a container in the old way is used mainly in places where it's impossible to use dependency injection. For example, in the form fields, models, or page-type classes. Those cannot be changed because they are not services.

In my opinion, this rule should be disabled completely, or it should somehow detect whether the class that will be changed is a service. Otherwise, every run would break the stuff.

**Comment by aschempp** [comment]
what rule exactly are you talking about?

**Comment by aschempp** [comment]
also see https://github.com/terminal42/contao-build-tools/blob/main/tools/rector/config.php#L62-L72

**Comment by qzminski** [comment]
Yeah it apparently is the `ContainerGetToConstructorInjectionRector` rule. Should this be then excluded on the project level?

**Comment by aschempp** [comment]
Who is adding it in the first place? What does your config look like?

**Comment by qzminski** [comment]
Not 100% sure, but I think the rule is added here: https://github.com/terminal42/contao-build-tools/blob/main/tools/rector/config.php#L69-L71

**Comment by aschempp** [comment]
yes, so it's not related to this rector, is it? 😉
