### ISSUE TITLE
Rewrite DCA image size options to service

### ISSUE THREAD

**Issue by aschempp** [contao/contao-rector#4]
**_Old:_**
```php
'imageSize' => array(
    'inputType' => 'imageSize',
    'options' => \System::getImageSizes(),
),
```

**_Old:_**
```php
'imageSize' => array(
    'inputType' => 'imageSize',
    'options' => \Contao\System::getContainer()->get('contao.image.sizes')->getAllOptions(),
),
```

**Comment by zoglo** [comment]
Stumbled across this issue and tried to implement this when I found out that the image size options were dropped due to the 'imageSize' widget adding the options now. 

Is this conversion still necessary or could we just drop the 'options' completely nowadays?

**Comment by aschempp** [comment]
This seems to be implemented in https://github.com/contao/contao-rector/pull/9 😎
